# Lists all of the BSPs we want to build for

# Example:
# [powerpc-mvme3100]
# networking = 'bsd'
# cfg = 'configs/rtems-config.mvme3100.ini' # Inferred

[powerpc-mvme3100]
networking = 'bsd'
net_services = true

# NOTE: Includes support for mvme5500
[powerpc-beatnik]
networking = 'bsd'
net_services = true

[powerpc-psim]
networking = 'none'
net_services = false

[i386-pc686]
networking = 'bsd'
net_services = true

# NOTE: Enable me if you want to test in ARM qemu!
#[arm-xilinx_zynq_a9_qemu]
#networking = 'bsd'
#net_services = true

[m68k-uC5282]
networking = 'legacy'
net_services = true
